services:
  latex-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/latex/src
      - ./build:/latex/build
    working_dir: /latex/src
    command: >
      -cd -pdf -interaction=nonstopmode -output-directory=/latex/build -pvc
      main.tex
